<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>preview</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsNotAsErrors>$(WarningsNotAsErrors);CA1031;CA1303;CA1308;CA1849;CA2007</WarningsNotAsErrors>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlcipher" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Aion.Infrastructure\Aion.Infrastructure.csproj" />
  </ItemGroup>
</Project>
